# Site settings
title: Leo个人博客
SEOTitle: 记录个人经验 - 知识更容易被记起
header-img: img/post-bg-desk.jpg
email: jgxiong@whu.edu.cn
description: "记录, 是为了更好地学习, 从此不再怕忘记自己学过的知识"
keyword: "Python, 量子化学, 日记, 笔记, 概率论"
url: "https://leojiageng.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/leojiageng/leojiageng.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you're going to be!"
sidebar-avatar: /img/HJ.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
# github_username:    qiubaiying
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: Ov23liDSnxG2NnVomzfD                            #生成的clientID
  clientSecret: cc5dc924d65e13dcba8506a68e50d4cb92000e98    #生成的clientSecret
  repo: leojiageng.github.io    #仓库名称
  owner: LeoJiaGeng    #github用户名
  admin: LeoJiaGeng
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接，请尽量不要删除，谢谢！
friends: [
    {
        title: "个人公众号",
        href: "https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4MzAyODk3OA==&action=getalbum&album_id=3424309186090336259&scene=126#wechat_redirect"
    },{
        title: "bilibili",
        href: "https://space.bilibili.com/506122452?spm_id_from=333.1007.0.0"
    },{
        title: "知乎：人造国际语",
        href: "https://zhuanlan.zhihu.com/Artificial-International-Language"
    }
]
